language: python
python:
  - "3.7"
  - "3.8"
before_install:
  - python --version
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --omit */virtualenv/* -m unittest discover
after_success:
  - coveralls
